# 1. Find the second largest element in a list (without using max() function).

In [2]:
n=list(map(int,input().split()))
n.sort()
print(n[-2])

 5 2 5 6 4 8 6


6


# 2.Check number is prime.

In [27]:
a=int(input())
c=0
for i in range(1,a+1):
    if a%i==0:
        c+=1
if c==2:
    print("Prime")
else:
    print("Not Prime")

 11


Prime


# 3. Reverse a string withount inbuilt functions

In [24]:
s=list(input())
n=len(s)
res=""
for i in range(1,n+1):
    res+=s[-(i)]
print(res)

 abc


cba


# 4. Merge two sorted arrays into a single sorted array without using any built-in sort methods.

In [29]:
a=[1,2,3,4]
b=[2,3,4,2]
for i in b:
    for j in range(0,len(a)):
        if i>=a[j]:
            a.insert(j+1,i)
            break
        elif a[j]<i:
            a.insert(j,i)
            break
print(a)
        
    


[1, 2, 4, 3, 2, 2, 3, 4]


# 5. Write a program to calculate the factorial of a number using recursion.

In [4]:
n=int(input())
def fact(n):
    if n>1:
        return n*fact(n-1)
    else:
        return n
print(fact(n))

 6


720


# 6. Find the largest contiguous subarray sum (Kadane’s Algorithm)

# 7. Check if a given string is a palindrome.

In [9]:
b=input()
def pal(b):
    n=len(b)
    res=""
    for i in range(1,n+1):
        res+=b[-(i)]
    return res
print(b==pal(b))

 abc


False


# 8. Convert a decimal number to binary without using built-in functions.

In [17]:
c=int(input())
binary=""
q=c
r=0
while q!=0:
    r=q%2
    binary+=str(r)
    q=q//2
print(binary[::-1])

 56


111000


 # 9.  Find pairs in an array with a given sum.

In [2]:
list1=list(map(int,input().split()))
k=int(input())
res=[]
for i in range(1,len(list1)):
    for j in range(i,len(list1)):
        if i+j==k:
            res.append((i,j))
print(res)

 1 2 1 5 2 1 3
 4


[(1, 3), (2, 2)]


# 10. Count the frequency of elements in a list.

In [5]:
d=list(map(int,input().split()))
key=int(input())
f=0
for i in d:
    if i==key:
        f+=1
print(f)

 1 2 1 5 2 1 2 3 
 1


3


# 11. Fibonacci sequence: Write a program to generate the first N numbers in the Fibonacci sequence using recursion

# 12. Remove duplicates from a list: Write a program to remove duplicate elements from a list while preserving the order of elements.

In [6]:
li=list(map(int,input().split()))
r=[]
for i in li:
    if i not in r:
        r.append(i)
print(r)

 1 2 4 5 2 1 1 2 3 5


[1, 2, 4, 5, 3]


# 13. Anagram check: Write a Python function that checks if two strings are anagrams of each other (i.e., if they contain the same characters in any order).

In [9]:
s1=input()
s2=input()
print(set(list(s1))==set(list(s2)))

 bcs
 bcn


False


# 14. Count vowels and consonants: Write a program that takes a string as input and counts the number of vowels and consonants in it.

In [10]:
o=["a","e","i","o","u","A","E","O","I","U"]
s=input()
a,b=0,0
for i in s:
    if i in o:
        a+=1
    else:
        b+=1
print(f"Vowels:{a} Consonants:{b}")

 sdmhfbaschewqi


Vowels:3 Consonants:11


# 15. Binary search algorithm: Implement the binary search algorithm for a sorted list and return the index of a target value.

In [11]:
lis=list(map(int,input().split()))
key=int(input())
lis.sort()
high=len(lis)
low=0
mid=len(lis)//2
while high<low:
    if key>lis[mid]:
        low=mid
        high=high
        mid=len(lis[low:high])//2
    elif key<lis[mid]:
        high=mid
        low=low
        mid=len(lis[low:high])//2
    else:
        print(lis[mid])


 5 4 5 6 4 2 3 4 6 5
 5


# 16. Check if a list is sorted: Write a function to check if a given list is sorted in ascending order

In [14]:
li=list(map(int,input().split()))
def sortedd(li):
    for i in range(0,len(li)-1):
        if li[i]>li[i+1]:
            return "Not Sorted"
    return "Sorted"

print(sortedd(li))

 2 1 3 5 2 1


Not Sorted


# 17. Transpose of a matrix: Given a matrix (2D list), write a Python function to calculate the transpose of the matrix.

In [15]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,3,1,5]])
print(np.transpose(arr))

[[1 5 9]
 [2 6 3]
 [3 7 1]
 [4 8 5]]


# 18. Sum of digits of a number: Write a recursive function to find the sum of digits of a given number

In [16]:
n=input()
s=0
for i in n:
    s+=int(i)
print(s)

 235


10


# 19. Intersection of two lists: Write a program that finds the intersection of two lists (i.e.,common elements between them)

In [21]:
import numpy as np
set1={1,2,4,3}
set2={5,1,2,3}
print(set1&set2)

{1, 2, 3}


# 20. Find all permutations of a string: Write a program to find all permutations of a given string.